language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  fqdn: kassellabs.io
  target_branch: master
  on:
    branch: master-pre-build
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
